### ISSUE TITLE
ビルドが成功しない

### ISSUE THREAD

**Issue by diffshare** [diffshare/issue-maps#1]
https://twitter.com/cat_in_136/status/682420271983144960

**Comment by cat-in-136** [comment]
:thumbsup:

```
root@6414c1e7e945:/tmp/issue-maps# npm install
npm info it worked if it ends with ok
npm info using npm@3.3.12
npm info using node@v5.3.0
npm info attempt registry request try #1 at 11:15:22 AM
npm http request GET https://registry.npmjs.org/fsevents
npm http 304 https://registry.npmjs.org/fsevents
npm WARN install Couldn't install optional dependency: Unsupported
npm info lifecycle issue-maps@1.0.0~preinstall: issue-maps@1.0.0
npm info linkStuff issue-maps@1.0.0
npm info lifecycle issue-maps@1.0.0~install: issue-maps@1.0.0
npm info lifecycle issue-maps@1.0.0~postinstall: issue-maps@1.0.0
npm info lifecycle issue-maps@1.0.0~prepublish: issue-maps@1.0.0
npm info ok 
```

Next stage!

```
root@6414c1e7e945:/tmp/issue-maps# node_modules/.bin/gulp build
[11:15:51] Requiring external module coffee-script/register
[11:15:51] Using gulpfile /tmp/issue-maps/gulpfile.coffee
[11:15:51] Starting 'build:ts'...
[11:15:52] Starting 'build:slim'...
[11:15:52] Starting 'build:sass'...
[11:15:52] Starting 'build:static'...
[11:15:52] Starting 'build:bower'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Gem sass is not installed.
root@6414c1e7e945:/tmp/issue-maps# git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

    node_modules/

nothing added to commit but untracked files present (use "git add" to track)
root@6414c1e7e945:/tmp/issue-maps# 
```

!!!

**Comment by cat-in-136** [comment]
gem sass 入れないといけないのか… docker だから一からいれないと

**Comment by diffshare** [comment]
readmeにgem install sass を書いておかないとね

**Comment by cat-in-136** [comment]
ruby のバージョン 2.1 は古すぎるのかな?

```
root@6414c1e7e945:/tmp/issue-maps# node_modules/.bin/gulp build
[11:35:49] Requiring external module coffee-script/register
[11:35:49] Using gulpfile /tmp/issue-maps/gulpfile.coffee
[11:35:49] Starting 'build:ts'...
[11:35:50] Starting 'build:slim'...
[11:35:50] Starting 'build:sass'...
[11:35:50] Starting 'build:static'...
[11:35:50] Starting 'build:bower'...
[11:35:50] Finished 'build:bower' after 14 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn slimrb ENOENT
  at exports._errnoException (util.js:855:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  at onErrorNT (internal/child_process.js:344:16)
  at nextTickCallbackWith2Args (node.js:455:9)
  at process._tickCallback (node.js:369:17)

root@6414c1e7e945:/tmp/issue-maps# gem list sass

*** LOCAL GEMS ***

sass (3.4.20)
root@6414c1e7e945:/tmp/issue-maps# ruby --version
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
```

**Comment by cat-in-136** [comment]
ん? slimrb は gem か?

**Comment by cat-in-136** [comment]
[gulp-slim](https://www.npmjs.com/package/gulp-slim)の指示に従って、`gem install slim -v '>= 3.0.2'`した後

```
root@6414c1e7e945:/tmp/issue-maps# node_modules/.bin/gulp
[11:42:47] Requiring external module coffee-script/register
[11:42:47] Using gulpfile /tmp/issue-maps/gulpfile.coffee
[11:42:47] Starting 'build:ts'...
[11:42:48] Starting 'build:slim'...
[11:42:48] Starting 'build:sass'...
[11:42:48] Starting 'build:static'...
[11:42:48] Starting 'build:bower'...
[11:42:48] Finished 'build:bower' after 16 ms
[11:42:48] Finished 'build:static' after 127 ms
src/js/Application.ts(1,1): error TS6053: File '/tmp/issue-maps/typings/tsd.d.ts' not found.
src/js/Application.ts(5,14): error TS2304: Cannot find name 'angular'.
src/js/Application.ts(19,24): error TS2503: Cannot find namespace 'ng'.
src/js/Application.ts(23,21): error TS2304: Cannot find name 'angular'.
src/js/Application.ts(39,30): error TS2503: Cannot find namespace 'ng'.
src/js/Application.ts(43,31): error TS2503: Cannot find namespace 'ng'.
src/js/Application.ts(43,72): error TS2503: Cannot find namespace 'ng'.
src/js/Application.ts(71,22): error TS2307: Cannot find module './Setting'.
src/js/directives/IssueDirective.ts(1,1): error TS6053: File '/tmp/issue-maps/typings/tsd.d.ts' not found.
src/js/directives/IssueDirective.ts(4,48): error TS2503: Cannot find namespace 'ng'.
src/js/directives/IssueDirective.ts(30,32): error TS2503: Cannot find namespace 'ng'.
src/js/directives/IssueDirective.ts(30,58): error TS2503: Cannot find namespace 'ng'.
src/js/directives/IssueDirective.ts(30,100): error TS2503: Cannot find namespace 'ng'.
src/js/directives/IssuesListDirective.ts(1,1): error TS6053: File '/tmp/issue-maps/typings/tsd.d.ts' not found.
src/js/directives/IssuesListDirective.ts(4,53): error TS2503: Cannot find namespace 'ng'.
src/js/directives/IssuesListDirective.ts(29,32): error TS2503: Cannot find namespace 'ng'.
src/js/directives/IssuesListDirective.ts(29,59): error TS2503: Cannot find namespace 'ng'.
src/js/directives/IssuesListDirective.ts(29,93): error TS2503: Cannot find namespace 'ng'.
src/js/directives/IssuesListDirective.ts(29,135): error TS2503: Cannot find namespace 'ng'.
src/js/directives/IssuesListDirective.ts(29,181): error TS2503: Cannot find namespace 'ng'.
src/js/directives/MapsDirective.ts(1,1): error TS6053: File '/tmp/issue-maps/typings/tsd.d.ts' not found.
src/js/directives/MapsDirective.ts(3,47): error TS2503: Cannot find namespace 'ng'.
src/js/directives/MapsDirective.ts(77,32): error TS2503: Cannot find namespace 'ng'.
src/js/directives/MapsDirective.ts(77,62): error TS2503: Cannot find namespace 'ng'.
src/js/directives/MapsDirective.ts(77,99): error TS2503: Cannot find namespace 'ng'.
src/js/directives/MapsDirective.ts(77,137): error TS2503: Cannot find namespace 'ng'.
src/js/directives/RootDirective.ts(1,1): error TS6053: File '/tmp/issue-maps/typings/tsd.d.ts' not found.
src/js/directives/RootDirective.ts(5,47): error TS2503: Cannot find namespace 'ng'.
src/js/directives/RootDirective.ts(20,32): error TS2503: Cannot find namespace 'ng'.
src/js/services/IssueService.ts(1,22): error TS2307: Cannot find module '../Setting'.
src/js/services/IssueService.ts(7,31): error TS2503: Cannot find namespace 'ng'.
src/js/services/IssueService.ts(7,64): error TS2503: Cannot find namespace 'ng'.
src/js/services/IssueService.ts(7,94): error TS2503: Cannot find namespace 'ng'.
src/js/services/IssueService.ts(10,19): error TS2503: Cannot find namespace 'ng'.
src/js/services/IssueService.ts(55,26): error TS2503: Cannot find namespace 'ng'.
src/js/services/IssueService.ts(76,58): error TS2503: Cannot find namespace 'ng'.
src/js/services/IssueService.ts(93,35): error TS2503: Cannot find namespace 'ng'.
src/js/services/IssueService.ts(97,9): error TS2304: Cannot find name 'angular'.
src/js/services/IssueService.ts(106,46): error TS2503: Cannot find namespace 'ng'.
[11:42:50] TypeScript: 39 semantic errors
[11:42:50] TypeScript: emit succeeded (with errors)

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Slim error in file (/tmp/issue-maps/src/html/index.slim):
Encoding::InvalidByteSequenceError: (__TEMPLATE__) is not valid US-ASCII
  Use --trace for backtrace.

root@6414c1e7e945:/tmp/issue-maps# npm list tsd  
npm info it worked if it ends with ok
npm info using npm@3.3.12
npm info using node@v5.3.0
issue-maps@1.0.0 /tmp/issue-maps
`-- (empty)
root@6414c1e7e945:/tmp/issue-maps#
```

tsdないからエラー起こるのは当たり前。

**Comment by diffshare** [comment]
travisのtestにgulp buildも必要だね

**Comment by diffshare** [comment]
検証ありがとう:D

**Comment by cat-in-136** [comment]
ある程度まで頑張ったけれど `tsd.json` が明らかに記載不足だから詰んだ。

```
root@6414c1e7e945:/tmp/issue-maps# git diff
diff --git a/.travis.yml b/.travis.yml
index b5d9ad0..2dee268 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,4 +5,8 @@ node_js:
   - "4.2.4"
   - "5.3.0"
   - node
-sudo: false
\ No newline at end of file
+before_install:
+  - gem update --system
+  - gem install sass
+  - gem install slim -v '>= 3.0.2'
+sudo: false
diff --git a/gulpfile.coffee b/gulpfile.coffee
index e7b7646..48bfdfc 100644
--- a/gulpfile.coffee
+++ b/gulpfile.coffee
@@ -4,6 +4,8 @@ del = require "del"
 fs = require "fs"
 packageJson = require "./package.json"

+tsd = require "gulp-tsd"
+
 #browserify = require "browserify"
 #watchify = require "watchify"
 watchify = require "gulp-watchify"
@@ -18,6 +20,7 @@ gulp.task "build", [
 ]
 gulp.task "build:pre", [
   #"build:coffee"
+  "build:tsd"
   "build:ts"
 ]

@@ -26,6 +29,9 @@ gulp.task "build:coffee", ->
   .pipe $.coffee()
   .pipe gulp.dest("lib")

+gulp.task "build:tsd", (callback) ->
+  tsd {command: "reinstall", config: "./tsd.json"}, callback
+
 gulp.task "build:ts", ->
   gulp.src "src/js/**/*.ts"
   .pipe $.typescript
diff --git a/package.json b/package.json
index aca8e9c..c6a0bd0 100644
--- a/package.json
+++ b/package.json
@@ -29,6 +29,7 @@
     "gulp-ruby-sass": "^2.0.6",
     "gulp-s3": "^0.3.0",
     "gulp-slim": "0.3.0",
+    "gulp-tsd": "0.0.4",
     "gulp-typescript": "^2.9.1",
     "gulp-watchify": "git://github.com/marcello3d/gulp-watchify.git",
     "vinyl-source-stream": "^1.1.0",
```

**Comment by diffshare** [comment]
あ，まずい，typingsを含めるのは筋が悪いか

**Comment by cat-in-136** [comment]
tsd.json の `installed` が空なのがまずい。typings そのものは含めないで良いものと思われ

**Comment by cat-in-136** [comment]
:+1: b46c082

Next stage...

```
root@6414c1e7e945:/tmp/issue-maps# node_modules/.bin/gulp      
[13:04:02] Requiring external module coffee-script/register
[13:04:02] Using gulpfile /tmp/issue-maps/gulpfile.coffee
[13:04:02] Starting 'build:tsd'...
[13:04:02] [gulp-tsd] execute command: reinstall
[13:04:02] [gulp-tsd] config: ./tsd.json
[13:04:02] Starting 'build:ts'...
[13:04:03] Starting 'build:slim'...
[13:04:03] Starting 'build:sass'...
[13:04:03] Starting 'build:static'...
[13:04:03] Starting 'build:bower'...
[13:04:03] Finished 'build:bower' after 17 ms
[13:04:03] [gulp-tsd] latest: undefined
[13:04:03] [gulp-tsd] running...
[13:04:03] Finished 'build:static' after 160 ms
src/js/Application.ts(71,22): error TS2307: Cannot find module './Setting'.
src/js/services/IssueService.ts(1,22): error TS2307: Cannot find module '../Setting'.
[13:04:06] TypeScript: 2 semantic errors
[13:04:06] TypeScript: emit succeeded (with errors)
Uncaught exception: { [Error: Slim error in file (/tmp/issue-maps/src/html/index.slim):
Encoding::InvalidByteSequenceError: (__TEMPLATE__) is not valid US-ASCII
  Use --trace for backtrace.
]
  message: 'Slim error in file (/tmp/issue-maps/src/html/index.slim):\nEncoding::InvalidByteSequenceError: (__TEMPLATE__) is not valid US-ASCII\n  Use --trace for backtrace.\n',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-slim',
  __safety: { toString: [Function: bound ] } }
```

SlimのデフォルトエンコードがUS-ASCIIとかいう米国からの参入障壁（違

ていうか、下のようにして travis-ci で gulp build しないと永遠にたどり着かない気がする。

``` diff
diff --git a/gulpfile.coffee b/gulpfile.coffee
index e7b7646..397aee2 100644
--- a/gulpfile.coffee
+++ b/gulpfile.coffee
@@ -96,6 +96,11 @@ gulp.task "watch", ["build", "enable-watch-mode", "connect"], ->
   gulp.watch "./src/html/**/*.slim",    ["build:slim"]
   gulp.watch "./src/css/**/*.sass",    ["build:sass"]

+gulp.task "test", [
+  "build"
+  # TODO test
+]
+
 gulp.task "default", ["build"]

 gulp.task "clean", del.bind(null, ["lib/*", "public/*"])
diff --git a/package.json b/package.json
index aca8e9c..2d9e8c6 100644
--- a/package.json
+++ b/package.json
@@ -4,7 +4,7 @@
   "description": "",
   "main": "index.js",
   "scripts": {
-    "test": "echo \"OK: npm install is OK\" && exit 0"
+    "test": "node_modules/.bin/gulp test"
   },
   "repository": {
     "type": "git",
```

**Comment by diffshare** [comment]
Thx! @cat-in-136, パッチをブランチ切って適用した．
Let's see https://travis-ci.org/diffshare/issue-maps

**Comment by diffshare** [comment]
slimの件はwindowsの場合はRUBYOPTSを"-Eutf-8"にして逃げたが，Linuxの場合はどうするんだろうか

**Comment by cat-in-136** [comment]
もう諦めた。やっぱり node はわからない。

```
root@6414c1e7e945:/tmp/issue-maps# RUBYOPTS=-Eutf-8 node_modules/.bin/gulp      
[14:59:18] Requiring external module coffee-script/register
[14:59:19] Using gulpfile /tmp/issue-maps/gulpfile.coffee
[14:59:19] Starting 'build:tsd'...
[14:59:19] [gulp-tsd] execute command: reinstall
[14:59:19] [gulp-tsd] config: ./tsd.json
[14:59:19] Starting 'build:slim'...
[14:59:19] Starting 'build:sass'...
[14:59:19] Starting 'build:static'...
[14:59:19] Starting 'build:bower'...
[14:59:19] Finished 'build:bower' after 17 ms
[14:59:19] [gulp-tsd] latest: undefined
[14:59:19] [gulp-tsd] running...
[14:59:19] Finished 'build:static' after 106 ms
Uncaught exception: { [Error: Slim error in file (/tmp/issue-maps/src/html/index.slim):
Encoding::InvalidByteSequenceError: (__TEMPLATE__) is not valid US-ASCII
  Use --trace for backtrace.
]
  message: 'Slim error in file (/tmp/issue-maps/src/html/index.slim):\nEncoding::InvalidByteSequenceError: (__TEMPLATE__) is not valid US-ASCII\n  Use --trace for backtrace.\n',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-slim',
  __safety: { toString: [Function: bound ] } }
root@6414c1e7e945:/tmp/issue-maps# 
```

**Comment by diffshare** [comment]
ああ，なるほど，LANG=Cだとコケるのか

**Comment by diffshare** [comment]
slimに関しては

```
LANG=ja_JP.utf-8 node_modules/.bin/gulp build:slim
```

をお試しください．
